### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by jbradt** [ExtremeScale/ThreadPool#1]
What build system is this using? I'm not familiar with it. (Aside from the Makefile, obviously.)

I might add a CMakeLists also, for variety's sake. (And since CMake is what I'm most familiar with.)

**Comment by csullivan** [comment]
Sure, go for it! It is just a Makefile with a separate defaults.inc which is included in the Makefile body. Thus, to build you just need to type make as usual. It quite advanced in that it custom builds all the rules for all the targets. So any headers and source files placed in include/src will be compiled to static objects and any code in the top level will be compiled into executables (that link against the objects). Additionally you can create a subdirectory libName, with separate include/src directories which will automatically be compiled to shared libraries that all executables will link against. Credit goes to Eric Lunderberg, it's a really nice build system.

**Comment by jbradt** [comment]
Ahh, I had suspected it might be Eric's magic makefile that I've heard so much about. I'll have to take a look at it some time since I ought to learn more about makefiles in general.
