### ISSUE TITLE
MapRange function has no effect

### ISSUE THREAD

**Issue by jbradt** [ExtremeScale/ThreadPool#2]
`ThreadPool::MapRange` function captures the callable `func` by value, duplicating any data it contains. Capturing by reference in the lambda causes it to crash.

**Comment by csullivan** [comment]
Awesome! I was thinking it would be great to test passing a std::function to be used as the callable serial function for the for loop. I decided as a first go (in ThreadPool::ParallelFor) to go with a static class function call using templates to start. I assume there is some overhead with std::function, as compared to a regular function, so this would be pretty interesting to compare, and something worth mentioning in the project write up.

Another thought I had was to create a general templated function that takes any callable type, and uses std::forward to forward the arguments to the caller. I am curious how all of these methods compare in performance.
