### ISSUE TITLE
Callable lambda faster than c-style function pointer?

### ISSUE THREAD

**Issue by csullivan** [ExtremeScale/ThreadPool#4]
See example.cc, here are the results:

Callable: c-function pointer
Trial 0: 545.396 ms
Trial 1: 546.575 ms
Trial 2: 524.65 ms
Trial 3: 525.346 ms
Trial 4: 527.658 ms
Trial 5: 522.466 ms
Trial 6: 522.309 ms
Trial 7: 522.094 ms
Trial 8: 522.489 ms
Trial 9: 522.05 ms
Average: 528.103 ms

Callable: lambda function (without capture)
Trial 0: 504.812 ms
Trial 1: 504.465 ms
Trial 2: 505.018 ms
Trial 3: 504.425 ms
Trial 4: 504.08 ms
Trial 5: 502.733 ms
Trial 6: 503.574 ms
Trial 7: 503.58 ms
Trial 8: 503.331 ms
Trial 9: 503.356 ms
Average: 503.937 ms

Wat? Also see results from std-thread_v_openmp (*.out files). The average for the lambda case here is almost exactly the performance I see with openmp! 

Also, the ThreadsafeQueue's performance is identical with that of the unfactored code from earlier on (tested it), and it's much easier to use/extendable. So good work!

**Comment by jbradt** [comment]
I just ran your example on my computer, and I don't always see the same behavior. If I run it multiple times, I get different results:

One run gave this:

```
Callable: c-function pointer
Trial 0: 12.7304 ms
Trial 1: 12.4253 ms
Trial 2: 12.8297 ms
Trial 3: 14.177 ms
Trial 4: 14.2978 ms
Trial 5: 12.6585 ms
Trial 6: 13.3145 ms
Trial 7: 13.2731 ms
Trial 8: 14.1199 ms
Trial 9: 12.5356 ms
Average: 13.2362 ms

Callable: lambda function (without capture)
Trial 0: 13.5192 ms
Trial 1: 13.0618 ms
Trial 2: 13.3688 ms
Trial 3: 13.3597 ms
Trial 4: 14.0236 ms
Trial 5: 12.401 ms
Trial 6: 12.7183 ms
Trial 7: 13.5576 ms
Trial 8: 13.8656 ms
Trial 9: 12.4862 ms
Average: 13.2362 ms
```

While another run gave this:

```
Callable: c-function pointer
Trial 0: 12.6599 ms
Trial 1: 12.4872 ms
Trial 2: 12.8678 ms
Trial 3: 14.1417 ms
Trial 4: 13.3931 ms
Trial 5: 13.0923 ms
Trial 6: 13.5415 ms
Trial 7: 14.8254 ms
Trial 8: 12.5579 ms
Trial 9: 12.7005 ms
Average: 13.2267 ms

Callable: lambda function (without capture)
Trial 0: 14.2848 ms
Trial 1: 13.3292 ms
Trial 2: 12.4048 ms
Trial 3: 12.8115 ms
Trial 4: 13.8595 ms
Trial 5: 13.29 ms
Trial 6: 12.5059 ms
Trial 7: 12.7723 ms
Trial 8: 13.0553 ms
Trial 9: 12.6159 ms
Average: 13.0929 ms
```

(Note that I reduced the size of the arrays from 1e9 to 1e7 after I ran it once and it tried to allocate literally all of my Mac's memory...) 

I will also take a look at the assembly. 

[This SO answer](http://stackoverflow.com/a/19371276/3820658) doesn't actually address this problem, but it was interesting nonetheless since the author mentioned that lambdas were mysteriously faster. They did, however, say that std::function's overhead is negligible (only a few instructions).

**Comment by csullivan** [comment]
I had read this post before, so it was floating around in my mind last night, thanks for linking it to me. I agree that a std::function is only a few extra instructions, but my naive assumption was that since a std::function would be called N times (1e9 in the example), that this could add up quite a bit. But more investigation clearly is needed..

**Comment by csullivan** [comment]
Ok, so your results are roughly comparable between the two. What if you do one that takes a bit longer? i.e. hundreds of milliseconds?

**Comment by csullivan** [comment]
Lambdas end up being faster because they are easier for the compiler to inline.
