### ISSUE TITLE
Issue with master_is_worker model

### ISSUE THREAD

**Issue by csullivan** [ExtremeScale/ThreadPool#6]
I noticed just now that since the merge making the master thread also a worker, that their is a deadlock occurring with small N. I am not sure why at the moment. Rolling back to before the merge (corresponding commit) removes the issue.

**Comment by jbradt** [comment]
I'm looking into this. I suspect there might be a problem in the ThreadsafeQueue where I notify the workers before releasing the lock (see the line with the comment):

``` C++
T pop()
{
    std::unique_lock<std::mutex> lock(m_qmtx);
    m_cond.wait(lock, [this]{ return !m_contents.empty() || m_finished; });
    if (m_finished) throw QueueFinished();
    T item = std::move(m_contents.front());
    m_contents.pop();
    m_cond.notify_all();  // I'm not sure if this can be called before the return...
    return item;
}
```

I'll post again if I find anything.
